=== ThallesP/railway-bookmarklets/bookmarklets/meta_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
      "short_title": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "header_subtext": {
        "type": "string"
      },
      "bookmarklet_link_text": {
        "type": "string"
      },
      "include_instructions": {
        "type": "boolean"
      },
      "custom_instructions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "short_title",
      "title",
      "bookmarklet_link_text",
      "include_instructions"
    ]
  }

=== ThallesP/railway-bookmarklets/_deleted/service-embed-v1/meta.json
{
    "short_title": "Service Embed v1",
    "title": "Embed Service Into v1 Template Composer",
    "header_subtext": "This bookmarklet will embed a service from a given v1 template into the v1 template currently being edited",
    "bookmarklet_link_text": "Embed Service v1",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template edit page you want to embed a service into",
        "Click on the bookmarklet"
    ]
}

=== ThallesP/railway-bookmarklets/bookmarklets/template-info/meta.json
{
    "$schema": "../meta_schema.json",
    "short_title": "Template Info",
    "title": "Template Info",
    "header_subtext": "This bookmarklet will show you the template in json format",
    "bookmarklet_link_text": "Template Info",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template page you wish to view the json for",
        "Click on the bookmarklet"
    ]
}

=== ThallesP/railway-bookmarklets/_deleted/set-service-icon/meta.json
{
    "short_title": "Set Service Icon",
    "title": "Set Service Icon v1",
    "header_subtext": "Sets a service icon for the specified service in the v1 template composer",
    "bookmarklet_link_text": "Set Service Icon",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template edit page",
        "Click on the bookmarklet"
    ]
}

=== ThallesP/railway-bookmarklets/_deleted/service-embed/meta.json
{
    "short_title": "Service Embed",
    "title": "Embed Service Into Template Composer",
    "header_subtext": "This bookmarklet will embed a service from a given template into the template currently being edited",
    "bookmarklet_link_text": "Embed Service",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template edit page you want to embed a service into",
        "Click on the bookmarklet"
    ]
}

=== ThallesP/railway-bookmarklets/bookmarklets/template-clone/meta.json
{
    "$schema": "../meta_schema.json",
    "short_title": "Template Clone",
    "title": "Template Clone",
    "header_subtext": "This bookmarklet will clone a template into your personal templates",
    "bookmarklet_link_text": "Clone Template",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template page you wish to clone",
        "Click on the bookmarklet"
    ]
}

=== ThallesP/railway-bookmarklets/_deleted/template-clone/meta.json
{
    "short_title": "v2 Template Clone",
    "title": "v2 Template Clone",
    "header_subtext": "This bookmarklet will clone a v2 template into your personal templates",
    "bookmarklet_link_text": "Clone v2 Template",
    "include_instructions": true,
    "custom_instructions": [
        "Drag the link to your bookmarks bar",
        "Open the template page you wish to clone",
        "Click on the bookmarklet"
    ]
}
